server:
  tomcat:
    threads:
      max: 10
  port: 8081
logging:
  level:
    org.*: info
spring:
  rocketmq:
    enable: true
    namesrvAddr: 127.0.0.1:9876
    producerGroup: shouguouo4j
    consumerGroup: shouguouo4j
    topic: shouguouo4j
config:
  enable: true
  host: 127.0.0.1
  port: 8081

log-record:
  data-pipeline: rocketMq
  rocket-mq-properties:
    topic: logRecord
    tag:
    group-name: logRecord
    namesrv-addr: 127.0.0.1:9876